apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-app
    spec:
      containers:
        - name: todo-app
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
