apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: todo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
