apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
data:
  mysql-password: {{ .Values.mysqlPassword | b64enc | quote }}
  mysql-root-password: {{ .Values.mysqlRootPassword | b64enc | quote }}
